CC=g++
CFLAGS=-c -O3 -Wall --std=c++2a -fmax-errors=2 #-Wfatal-errors
SOURCES=interpreter/bfint.cc

OBJECTS=$(SOURCES:.cc=.o)
EXECUTABLE=bfint

all:	$(SOURCES) $(EXECUTABLE) 

$(EXECUTABLE):$(OBJECTS)
	$(CC) $(OBJECTS) -o ../$@

.cc.o:
	$(CC) $(CFLAGS) $< -o $@


