CC=g++
CFLAGS=-c -Wall --std=c++2a -fmax-errors=2 #-Wfatal-errors
GENERATED_FILES=compiler_bisoncpp_generated.cc lex_flexcpp_generated.cc
MY_FILES=main.cc scanner.cc compiler.cc memory.cc bfxfunction.cc bfgenerator.cc typesystem.cc
SOURCES=$(GENERATED_FILES) $(MY_FILES)

OBJECTS=$(SOURCES:.cc=.o)
EXECUTABLE=bfx

all:	$(SOURCES) $(EXECUTABLE) 

$(EXECUTABLE):	$(OBJECTS)
	$(CC) $(OBJECTS) -o $@ 

.cc.o:
	$(CC) $(CFLAGS) $< -o $@ -DBFX_DEFAULT_INCLUDE_PATH=$(BFX_DEFAULT_INCLUDE_PATH)

